[package]
name = "find_doubles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.21"
#fasthash = "0.4.0"
glob = "0.3.1"
meowhash = "0.3.0"
